# Generated by Django 2.1.7 on 2019-04-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
